spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daehak-ro?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail.username} # 3
    password: ${mail.password} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          # timeout: 5000 # 6
          starttls:
            enable: true # 7

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
jwt:
  secret: "김승우짱임  ㅋ ㅋ"
  expiration-time: 864000000 # 하루 추후 변경
  token-prefix: "test"
  header-string: "Authorization"